### ISSUE TITLE
conda environment file for installation

### ISSUE THREAD

**Issue by pdimens** [stuartwillis/poolparty#3]
This is the first of what will hopefully be two steps that ultimately lead to a simple conda-based installation.

### install with file
```bash
mamba env create --name poolparty --file poolparty.yaml
```

### the environment file `poolparty.yaml`
```yaml
name: poolparty
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bioconda::bbmap
  - bioconda::bcftools
  - bioconda::bioconductor-biobase
  - bioconda::bioconductor-biocgenerics
  - bioconda::bioconductor-multtest
  - bioconda::bioconductor-qvalue
  - bioconda::bwa
  - bioconda::fastqc
  - bioconda::perl-text-nsp
  - bioconda::popoolation2
  - bioconda::picard
  - bioconda::samblaster
  - bioconda::samtools
  - conda-forge::dos2unix
  - conda-forge::parallel
  - conda-forge::r-ape
  - conda-forge::r-bibtex
  - conda-forge::r-data.table
  - conda-forge::r-fbasics
  - conda-forge::r-gbrd
  - conda-forge::r-ggplot2
  - conda-forge::r-mass
  - conda-forge::r-matrixstats
  - conda-forge::r-metap
  - conda-forge::r-plyr
  - conda-forge::r-rcolorbrewer
  - conda-forge::r-rdpack
  - conda-forge::r-reshape
  - conda-forge::r-stringr
  - conda-forge::r-survival
  - conda-forge::r-tidyr

```
