### ISSUE TITLE
conda-based installation

### ISSUE THREAD

**Issue by pdimens** [stuartwillis/poolparty#4]
This serves to hopefully set the infrastructure to a fully conda-based installation, making it easier for people to get started with PoolParty2. The bioconda recipe has two parts:
1. The `meta.yaml` file which sets up all the build and runtime conditions, package info, etc.
2. The `build.sh` file of manual build steps

### meta.yaml
```yaml
{% set version = "" %}
{% set sha256 = "" %}

package:
  name: poolparty
  version: '{{ version }}'

source:
  url: https://github.com/stuartwillis/poolparty/releases/download/{{ version }}/poolparty.{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('poolparty', max_pin="x") }}

requirements:
  run:
    - bbmap
    - bcftools
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-multtest
    - bioconductor-qvalue
    - bwa
    - fastqc
    - perl-text-nsp
    - picard
    - popoolation2
    - samblaster
    - samtools
    - dos2unix
    - parallel
    - r-ape
    - r-bibtex
    - r-data.table
    - r-fbasics
    - r-gbrd
    - r-ggplot2
    - r-mass
    - r-matrixstats
    - r-metap
    - r-plyr
    - r-rcolorbrewer
    - r-rdpack
    - r-reshape
    - r-stringr
    - r-survival
    - r-tidyr

test:
  commands:
    - "poolparty"

about:
  home: "https://github.com/stuartwillis/poolparty/"
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: "A BASH pipeline to align and analyze paired-end NGS data on a genome assembly"
  dev_url: "https://github.com/stuartwillis/poolparty"

extra:
  recipe-maintainers:
    - stuartwillis
```

### build.sh
```bash
# bbmap files
cp {WHEREVER THOSE FILES ARE} ${PREFIX}

# move poolparty scripts to PATH
chmod +x {WHICHEVER SCRIPTS}
cp {WHICHEVER SCRIPTS} ${PREFIX}
```
